export {
  initOneSignalSafe as init,
  requestPermissionManual as requestPermission,
  logoutUser,
  getExistingSubscriptionId,
  waitForSubscription,
  onNotificationClicked,
  startSubscriptionSync,
  stopSubscriptionSync,
  getPermissionStatus as getPermissionState,
  getDiagnostics,
  getDeviceInfo,
  isPushSupported,
  ensureExternalId,
  verifyAndRecover,
  saveSubscriptionToBackend,
} from "../utils/notificationPermissionManager";
